---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# Verifies action/workflow calls are pinned to SHA commit values
name: 📌 [R] Audit GitHub Actions

# yamllint disable-line rule:truthy
on:
  workflow_call:

permissions: {}

jobs:
  check-actions:
    name: Pinned Versions
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Check Pinned Versions
        # yamllint disable-line rule:line-length
        uses: lfit/releng-reusable-workflows/.github/actions/pinned-versions-action@fd9bc3881956c2645d4da312079580d331f562ed # v0.2.2
