---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2023 The Linux Foundation

name: Lint GitHub Actions workflows

# yamllint disable-line rule:truthy
on: [push, pull_request]

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        id: get_actionlint
        # yamllint disable-line rule:line-length
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash

  commit-message:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for amannn/action-semantic-pull-request to analyze PRs
      statuses: write  # for amannn/action-semantic-pull-request to mark status of analyzed PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Check PR for semantic commit message
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Requires the type to be capitlized, but accept any of the standard
          # types
          types: |
            Fix
            Feat
            Chore
            Docs
            Style
            Refactor
            Perf
            Test
            Revert
            CI
            Build
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # checkout at the last commit
          ref: ${{ github.event.pull_request.head.sha }}
          # get all history
          fetch-depth: 0

      - name: Install gitlint
        shell: bash
        run: |
          python -m pip install gitlint

      - name: Run gitlint
        shell: bash
        run: |
          gitlint --commits "${{ github.event.pull_request.base.sha }}..HEAD"
